### ISSUE TITLE
tailwind.config.js extend config doesn't work

### ISSUE THREAD

**Issue by danestves** [flayyer/create-flayyer-app#2]
I have extended my `tailwind.config.js` like this:

```js
module.exports = {
  purge: {
    enabled: process.env.NODE_ENV === "production",
    content: [
      "./templates/**/*.ts",
      "./templates/**/*.tsx",
      "./templates/**/*.js",
      "./templates/**/*.jsx",
      "./components/**/*.ts",
      "./components/**/*.tsx",
      "./components/**/*.js",
      "./components/**/*.jsx",
      "./styles/**/*.css",
      "./styles/**/*.scss",
      "./styles/**/*.sass",
      "./styles/**/*.less",
    ],
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      colors: {
        secondary: "#071d49",
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
```

And if i hover in the class, is detected by Tailwind CSS Intellisense in a correct way

![image](https://user-images.githubusercontent.com/31737273/107886530-c90c1100-6ed6-11eb-814e-31f637229847.png)

The problem is that is not being rendered in the browser

![image](https://user-images.githubusercontent.com/31737273/107886561-e93bd000-6ed6-11eb-88a9-edcd0e4a1f90.png)

All the rest of the default classes works, but if i add a custom class it's like doesn't compile

**Comment by lopezjurip** [comment]
Looks like this is an issue with Parcel v1 + Tailwind, we will see if we can fix it or wait for Parcel 2 support. Also we are thinking about using https://github.com/vitejs/vite or https://www.snowpack.dev/ but we need more time to experiment

**Comment by lopezjurip** [comment]
Try installing `@fullhuman/postcss-purgecss` as a development dependency. Looks like it solves the problem.

```sh
yarn add --dev @fullhuman/postcss-purgecss
```

Let me know if that works for you

**Comment by danestves** [comment]
Hi @lopezjurip ! I made to fix the problem updating my dependencies and using the [compatibility build](https://tailwindcss.com/docs/installation#post-css-7-compatibility-build) and all work together very well, i suggest to bring that to the `react-typescript-tailwind` template maybe? because when i update my dependencies the terminal says:

`Error: PostCSS plugin tailwindcss requires PostCSS 8.`

I made to fix the problem making this change, like we say in latin america two birds of one shot, i fix the error of the postcss plugin and also the error of not taking the tailwind config ✨
